from flask import Flask, request, jsonify
from flask_cors import CORS
import pickle
import numpy as np
import pandas as pd
import os

app = Flask(__name__)
CORS(app)

# ─── Load model artifacts ────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH   = os.path.join(BASE_DIR, "models", "best_airbnb_model.pkl")
SCALER_PATH  = os.path.join(BASE_DIR, "models", "scaler.pkl")
ENCODER_PATH = os.path.join(BASE_DIR, "models", "encoder.pkl")
FEATURES_PATH = os.path.join(BASE_DIR, "models", "features.pkl")

# Note: These files are generated by running updated.ipynb
METRICS_PATH = os.path.join(BASE_DIR, "models", "metrics.pkl")
metrics = {}
try:
    model    = pickle.load(open(MODEL_PATH,   "rb"))
    scaler   = pickle.load(open(SCALER_PATH,  "rb"))
    encoder  = pickle.load(open(ENCODER_PATH, "rb"))
    features = pickle.load(open(FEATURES_PATH, "rb"))
    
    if os.path.exists(METRICS_PATH):
        metrics = pickle.load(open(METRICS_PATH, "rb"))
    else:
        # Fallback if metrics.pkl is not yet generated
        metrics = {"r2_score": 0.9422, "model_name": "XGBoost"}
except Exception as e:
    print(f"Warning: Failed to load model artifacts: {e}")
    # Use dummy data or handle gracefully if not found yet
    model, scaler, encoder, features = None, None, None, []
    metrics = {"r2_score": 0.0, "model_name": "None"}

USD_TO_INR = 95.0

# ─── Feature metadata (for frontend reference) ───────────────────────────────
FEATURE_META = {
    "property_type": {
        "type": "categorical",
        "options": ["Apartment", "House", "Condominium", "Townhouse", "Loft",
                    "Villa", "Guest suite", "Bed and breakfast", "Bungalow",
                    "Cabin", "Hostel", "Hotel", "Other"]
    },
    "room_type": {
        "type": "categorical",
        "options": ["Entire home/apt", "Private room", "Shared room"]
    },
    "accommodates": {"type": "number", "min": 1, "max": 16, "default": 2},
    "bathrooms":    {"type": "number", "min": 0, "max": 10, "step": 0.5, "default": 1},
    "bed_type": {
        "type": "categorical",
        "options": ["Real Bed", "Pull-out Sofa", "Airbed", "Couch", "Futon"]
    },
    "cancellation_policy": {
        "type": "categorical",
        "options": ["flexible", "moderate", "strict", "super_strict_30", "super_strict_60"]
    },
    "cleaning_fee": {"type": "boolean", "options": ["True", "False"], "default": "True"},
    "city": {
        "type": "categorical",
        "options": ["NYC", "LA", "SF", "DC", "Chicago", "Boston", "Austin", "Seattle", "Denver", "Miami"]
    },
    "first_review":  {"type": "number", "min": 2000, "max": 2024, "default": 2018},
    "host_has_profile_pic": {"type": "boolean", "options": ["True", "False"], "default": "True"},
    "host_identity_verified": {"type": "boolean", "options": ["True", "False"], "default": "True"},
    "host_response_rate": {"type": "number", "min": 0, "max": 100, "default": 90},
    "host_since": {"type": "number", "min": 2008, "max": 2024, "default": 2016},
    "instant_bookable": {"type": "boolean", "options": ["True", "False"], "default": "False"},
    "last_review":   {"type": "number", "min": 2000, "max": 2024, "default": 2023},
    "thumbnail_url": {"type": "boolean", "options": ["True", "False"], "default": "True"},
    "bedrooms":      {"type": "number", "min": 0, "max": 10, "default": 1},
    "beds":          {"type": "number", "min": 0, "max": 16, "default": 1},
    "amenities_count": {"type": "number", "min": 0, "max": 100, "default": 15},
}


def preprocess_input(raw: dict) -> pd.DataFrame:
    """Convert raw form data to model-ready dataframe."""
    # Create copy of dict to modify
    data = raw.copy()
    
    # 1. Handle known boolean string conversions
    bool_cols = ("cleaning_fee", "host_has_profile_pic", 
                 "host_identity_verified", "instant_bookable", "thumbnail_url")
    for feat in bool_cols:
        if feat in data:
            val = str(data[feat]).lower()
            data[feat] = 1.0 if val in ("true", "t", "1", "yes") else 0.0

    # Convert input to DataFrame
    df = pd.DataFrame([data])

    # 2. Handle Categorical Encoding (for property_type, city, etc.)
    if encoder:
        df = encoder.transform(df)

    # 3. Ensure all columns match the model's feature set
    for col in features:
        if col not in df.columns:
            df[col] = 0.0

    # 4. Final reordering and selection
    # (Extract numeric values and ensure they are floats)
    df_final = df[features].apply(pd.to_numeric, errors='coerce').fillna(0).astype(float)
    
    return df_final


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "features": features})


@app.route("/predict", methods=["POST"])
def predict():
    try:
        raw = request.get_json(force=True)
        if not raw:
            return jsonify({"error": "No JSON payload received"}), 400

        df = preprocess_input(raw)
        scaled = scaler.transform(df)
        log_price = model.predict(scaled)[0]

        price_usd = float(np.exp(log_price))
        price_inr = round(price_usd * USD_TO_INR, 2)
        price_usd = round(price_usd, 2)

        return jsonify({
            "success": True,
            "price_usd": price_usd,
            "price_inr": price_inr,
            "log_price": round(float(log_price), 4),
            "r2_score": round(metrics.get("r2_score", 0.0), 4),
            "model_used": metrics.get("model_name", "Unknown")
        })

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route("/features", methods=["GET"])
def get_features():
    return jsonify({"features": features, "meta": FEATURE_META})


if __name__ == "__main__":
    app.run(debug=True, port=5000)
